name: base_architecture_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  flutter_screenutil: ^5.9.0

  shared_preferences: ^2.2.2
  connectivity_plus: ^4.0.2

  firebase_crashlytics: ^3.4.17
  firebase_analytics: ^10.8.8
  firebase_core: ^2.27.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/icons/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: OpenSansRegular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf